version: '2.4'

services:

  adventureworks:
    image: phillipsj/adventureworks
    container_name: adventureworks
    ports:
      - target: 1433
        published: 1433
        protocol: tcp
        mode: host
    environment:
      ACCEPT_EULA: "Y"
    mem_limit: 4g
    mem_reservation: 2g
    weight: 700

  schemacrawler:
    image: schemacrawler/schemacrawler
    container_name: schemacrawler
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/schcrwlr/output
    entrypoint: /bin/bash
