name: Validate

on: push

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2        
    - id: show-environment
      name: Show environment
      run: |
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        echo github.workspace: ${{ github.workspace }}        

# LINT CODE
    - id: lint-code-base
      name: Lint Code Base
      uses: docker://github/super-linter:v5.0.0
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_XML: true
        VALIDATE_MD: true
        VALIDATE_BASH: true
        VALIDATE_PYTHON: false
        VALIDATE_RUBY: false
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_DOCKER: true
        VALIDATE_CSS: true
        VALIDATE_ENV: true
